### ISSUE TITLE
findSignatures problem

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/deconvR#21]
https://github.com/BIMSBbioinfo/deconvR/blob/19a3b0f42aa10c7c7c4fbcd52d585f3168fed1f2/R/findSignatures.R#L43
I don't fully understand what this function does? it looks like its filtering based on variation cutoff but that's not what we usually mean by signatures

**Comment by igunduz** [comment]
`findSignatures` is used to extend a reference atlas by using another atlas. If you have multiple samples from the same cell type, it ignores CpGs with variation > `variation_cutoff `with that cell type. In the example, since we don't have an additional reference atlas, we use simulated samples created by `simulateCellMix`  as `new_cell_type` to show as an example. In summary, the function _finds the signatures_ of a given new atlas/samples of cell types and, extend reference atlas aka _signature matrix_

**Comment by al2na** [comment]
but signature matrix should contain cell type specific markers, I don't think this method can get such markers, can it? from the function name, I would expect that it uses some statistical test or a method to detect cell-type-specific markers

**Comment by igunduz** [comment]
You're right, it doesn't function to extract cell-type specific markers. It only works if you have existed signature matrix and, want to add more cell-types information without disrupting the ID variance, in example case Cpg variance
